# Generated by Django 2.2 on 2019-06-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('cam_id', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('longitude', models.CharField(default=None, max_length=10)),
                ('latitude', models.CharField(default=None, max_length=10)),
                ('province', models.CharField(default=None, max_length=20)),
                ('sequence', models.CharField(default=None, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('road_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('pass_id', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('plate_char', models.CharField(max_length=1)),
                ('plate_num', models.CharField(max_length=7)),
                ('speed', models.CharField(blank=True, max_length=3, null=True)),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
                ('longitude', models.CharField(default=None, max_length=10)),
                ('latitude', models.CharField(default=None, max_length=10)),
                ('camera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Camera')),
                ('road', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Road')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='road',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Road'),
        ),
    ]
