# Generated by Django 2.2 on 2019-06-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190609_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='pass',
            name='day',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pass',
            name='month',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pass',
            name='year',
            field=models.IntegerField(default=None),
        ),
    ]
